In [4]:
import numpy

In [6]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [7]:
import numpy as np

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a = np.arange(15).reshape(3,5)

In [22]:
a.ndim

2

In [26]:
a.dtype.name

'int32'

In [28]:
a.size

15

In [30]:
a = np.arange(15).reshape(3,5)
type(a)
b = np.array([1,2,3])
type(b)

numpy.ndarray

In [31]:
type(a)

numpy.ndarray

In [32]:
type(b)

numpy.ndarray

In [38]:
c=np.array([1,2,3], dtype='float64')

In [40]:
c

array([ 1.,  2.,  3.])

In [39]:
c.dtype

dtype('float64')

In [46]:
np.zeros( (3,4) , dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
np.ones((10,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [58]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [60]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [71]:
np.arange(24).reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
a = np.arange(24).reshape(3,2,4)

In [80]:
b = np.arange(24)

In [82]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [83]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
import random

In [88]:
b = np.arange(random.randrange(1,24,24))

In [89]:
b

array([0])

In [98]:
a = np.arange(10).reshape(2,5)

In [99]:
a**3

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

In [118]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
a[:,0]

array([0, 5])