In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [3]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [4]:

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [10]:

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(10001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22656.0 
Prediction:
 [[ 22.04806328]
 [ 21.61978722]
 [ 24.09669304]
 [ 22.29300499]
 [ 18.6339016 ]]
1000 Cost:  4.18461 
Prediction:
 [[ 154.8938446 ]
 [ 182.59112549]
 [ 182.02253723]
 [ 194.41615295]
 [ 141.61683655]]
2000 Cost:  3.17888 
Prediction:
 [[ 154.35929871]
 [ 182.95117188]
 [ 181.8505249 ]
 [ 194.35540771]
 [ 142.03565979]]
3000 Cost:  2.56179 
Prediction:
 [[ 153.94538879]
 [ 183.22859192]
 [ 181.71565247]
 [ 194.31999207]
 [ 142.34735107]]
4000 Cost:  2.1722 
Prediction:
 [[ 153.62367249]
 [ 183.44303894]
 [ 181.60920715]
 [ 194.30371094]
 [ 142.57759094]]
5000 Cost:  1.91644 
Prediction:
 [[ 153.37239075]
 [ 183.60932922]
 [ 181.52456665]
 [ 194.30172729]
 [ 142.74588013]]
6000 Cost:  1.73985 
Prediction:
 [[ 153.17492676]
 [ 183.73883057]
 [ 181.45654297]
 [ 194.31034851]
 [ 142.86706543]]
7000 Cost:  1.61066 
Prediction:
 [[ 153.01873779]
 [ 183.84020996]
 [ 181.40139771]
 [ 194.32695007]
 [ 142.95256042]]
8000 Cost:  1.51029 
Prediction:
 [[ 152.89407349

In [13]:
print(sess.run(hypothesis, feed_dict={X: [[73., 66., 70.]]}))

[[ 143.07128906]]
