In [2]:
import numpy as np

# numpy 튜토리얼 http://ishuca.tistory.com/373

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
print(type(a))  
print(a.shape) 

<class 'numpy.ndarray'>
(3,)


In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 2차원 배열 일때 안에 것만 가져오기
b[:1,:]

array([[1, 2, 3]])

In [21]:
b.shape

(2, 3)

In [23]:
# 파일에서 곧바로 읽기
# http://blog.naver.com/PostView.nhn?blogId=radii26omg&logNo=221051465120&parentCategoryNo=&categoryNo=25&viewDate=&isShowPopularPosts=true&from=search
np.genfromtxt('./data/apply.dat', delimiter=',')

array([ 5080073.,  5395180.,  2993051., ...,  4428959.,  4500114.,
        3628724.])

In [31]:
np.genfromtxt('./data/new.txt', delimiter='\t')

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  2.],
       [ 4.,  2.],
       [ 4.,  3.]])

In [31]:
np.genfromtxt('./data/github_commits.csv', delimiter=',')[:3]

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,   0.,   1.,   0.,   1.,   1.,   0.],
       [ nan,   0.,   1.,   0.,   4.,   0.,   0.]])

In [32]:
np.genfromtxt('./data/github_commits.csv', delimiter=',', dtype=None)[:3]

array([[b'date', b'yjo2lee', b'chanha22', b'pixar0407', b'deyim',
        b'Rocket-Hyun', b'chloejiwon'],
       [b'2017-11-07', b'0', b'1', b'0', b'1', b'1', b'0'],
       [b'2017-11-08', b'0', b'1', b'0', b'4', b'0', b'0']],
      dtype='|S11')

In [30]:
np.genfromtxt('./data/github_commits.csv', delimiter=',')[1:,1:]

array([[  0.,   1.,   0.,   1.,   1.,   0.],
       [  0.,   1.,   0.,   4.,   0.,   0.],
       [  4.,   0.,   4.,   1.,  42.,   0.],
       [  0.,   1.,   1.,   3.,   1.,   0.],
       [  1.,   0.,   2.,   3.,   5.,   0.],
       [  1.,   1.,   1.,   1.,  11.,   1.],
       [  1.,   0.,   3.,   3.,   6.,   3.],
       [  1.,   0.,   4.,   4.,   1.,   2.],
       [  1.,   1.,   3.,   4.,   4.,   0.],
       [  1.,   1.,   1.,   4.,   5.,   5.],
       [  1.,   1.,   1.,   3.,   6.,   1.],
       [  0.,   0.,   1.,   1.,   1.,   1.],
       [  3.,   2.,   2.,   1.,   5.,   0.],
       [  1.,   0.,   1.,   1.,   6.,   1.],
       [  1.,   0.,   2.,   2.,   4.,   4.],
       [  1.,   0.,   3.,   3.,   0.,   1.],
       [  0.,   3.,   3.,   4.,  25.,   2.],
       [  1.,   2.,   1.,   1.,  49.,   0.],
       [  1.,   5.,   0.,   2.,   2.,   0.],
       [  1.,   2.,   1.,   1.,   1.,   2.],
       [  0.,  12.,   1.,   2.,   0.,   3.],
       [  1.,   5.,   0.,   2.,   9.,   5.],
       [  

In [19]:
# string으로 읽은 후 numpy로 읽기
fileName="./data/github_commits.csv"
# with open(fileName, "r", encoding="utf8") as f:
#     text = f.readlines()
# print(text)
textFile = open(fileName, "r", encoding="utf8")
text = textFile.readlines()
print(text)

['date,yjo2lee,chanha22,pixar0407,deyim,Rocket-Hyun,chloejiwon\n', '2017-11-07,0,1,0,1,1,0\n', '2017-11-08,0,1,0,4,0,0\n', '2017-11-09,4,0,4,1,42,0\n', '2017-11-10,0,1,1,3,1,0\n', '2017-11-11,1,0,2,3,5,0\n', '2017-11-12,1,1,1,1,11,1\n', '2017-11-13,1,0,3,3,6,3\n', '2017-11-14,1,0,4,4,1,2\n', '2017-11-15,1,1,3,4,4,0\n', '2017-11-16,1,1,1,4,5,5\n', '2017-11-17,1,1,1,3,6,1\n', '2017-11-18,0,0,1,1,1,1\n', '2017-11-19,3,2,2,1,5,0\n', '2017-11-20,1,0,1,1,6,1\n', '2017-11-21,1,0,2,2,4,4\n', '2017-11-22,1,0,3,3,0,1\n', '2017-11-23,0,3,3,4,25,2\n', '2017-11-24,1,2,1,1,49,0\n', '2017-11-25,1,5,0,2,2,0\n', '2017-11-26,1,2,1,1,1,2\n', '2017-11-27,0,12,1,2,0,3\n', '2017-11-28,1,5,0,2,9,5\n', '2017-11-29,1,1,1,2,0,0\n', '2017-11-30,3,0,0,2,0,3\n', '2017-12-01,2,2,4,1,2,0\n', '2017-12-02,4,2,1,2,1,1\n', '2017-12-03,1,1,4,3,1,0\n', '2017-12-04,1,3,1,1,3,1\n', '2017-12-05,1,2,1,1,1,3\n', '2017-12-06,1,0,4,1,7,2\n', '2017-12-07,0,0,4,1,2,3\n', '2017-12-08,1,0,1,1,1,0\n', '2017-12-09,1,2,1,1,7,1\n', '201

In [ ]:

textlist = textFile.read().split("\n")
textlist_range = textlist[1:len(textlist)-1]
# textlist_range[0].split(",")[1:]
# textnumpy = np.empty(6)
# numpy2 = np.empty(6)
# textnumpy
# np.concatenate(textnumpy,numpy2)
# for i in textlist_range:
#     np.append(textnumpy,i.split(",")[1:])
    
# textnumpy
#np.asarray(textFile.read().split("\n"))

#text = np.asarray(textFile.readlines())
#text