In [19]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [20]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]


In [21]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)


In [22]:

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

Tensor("add_20:0", dtype=float32)


In [32]:

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


In [34]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

        
        

0 Cost:  23944.7 
Prediction:
 [ 22.59580421  13.97583294  20.64156914  21.75433922   7.9406209 ]
1000 Cost:  21.5228 
Prediction:
 [ 157.74432373  180.28115845  182.49516296  198.21598816  135.58026123]
2000 Cost:  12.6585 
Prediction:
 [ 156.18484497  181.3523407   182.01997375  197.8515625   137.00346375]
3000 Cost:  7.49971 
Prediction:
 [ 154.99751282  182.1683197   181.65872192  197.57017517  138.09126282]
4000 Cost:  4.49627 
Prediction:
 [ 154.09399414  182.78970337  181.3843689   197.35215759  138.92326355]
5000 Cost:  2.74653 
Prediction:
 [ 153.40684509  183.26268005  181.17623901  197.18254089  139.56007385]
6000 Cost:  1.72606 
Prediction:
 [ 152.88467407  183.62252808  181.01861572  197.04995728  140.04801941]
7000 Cost:  1.12983 
Prediction:
 [ 152.48826599  183.89613342  180.89945984  196.94567871  140.42237854]
8000 Cost:  0.780495 
Prediction:
 [ 152.18772888  184.10395813  180.80961609  196.86305237  140.71003723]
9000 Cost:  0.574868 
Prediction:
 [ 151.96025085  18

In [35]:
# Testing our model
print(sess.run(hypothesis, feed_dict={x1: x1_data, x2: x2_data, x3: x3_data}))

[ 151.31767273  184.71875     180.56604004  196.50588989  141.67012024]
