In [65]:
import numpy as np
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [66]:
commit_array = np.genfromtxt('./data/github_commits.csv', delimiter=',')[1:,1:]

In [82]:
commit_array.tolist()

[[0.0, 1.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 4.0, 0.0, 0.0],
 [4.0, 0.0, 4.0, 1.0, 42.0, 0.0],
 [0.0, 1.0, 1.0, 3.0, 1.0, 0.0],
 [1.0, 0.0, 2.0, 3.0, 5.0, 0.0],
 [1.0, 1.0, 1.0, 1.0, 11.0, 1.0],
 [1.0, 0.0, 3.0, 3.0, 6.0, 3.0],
 [1.0, 0.0, 4.0, 4.0, 1.0, 2.0],
 [1.0, 1.0, 3.0, 4.0, 4.0, 0.0],
 [1.0, 1.0, 1.0, 4.0, 5.0, 5.0],
 [1.0, 1.0, 1.0, 3.0, 6.0, 1.0],
 [0.0, 0.0, 1.0, 1.0, 1.0, 1.0],
 [3.0, 2.0, 2.0, 1.0, 5.0, 0.0],
 [1.0, 0.0, 1.0, 1.0, 6.0, 1.0],
 [1.0, 0.0, 2.0, 2.0, 4.0, 4.0],
 [1.0, 0.0, 3.0, 3.0, 0.0, 1.0],
 [0.0, 3.0, 3.0, 4.0, 25.0, 2.0],
 [1.0, 2.0, 1.0, 1.0, 49.0, 0.0],
 [1.0, 5.0, 0.0, 2.0, 2.0, 0.0],
 [1.0, 2.0, 1.0, 1.0, 1.0, 2.0],
 [0.0, 12.0, 1.0, 2.0, 0.0, 3.0],
 [1.0, 5.0, 0.0, 2.0, 9.0, 5.0],
 [1.0, 1.0, 1.0, 2.0, 0.0, 0.0],
 [3.0, 0.0, 0.0, 2.0, 0.0, 3.0],
 [2.0, 2.0, 4.0, 1.0, 2.0, 0.0],
 [4.0, 2.0, 1.0, 2.0, 1.0, 1.0],
 [1.0, 1.0, 4.0, 3.0, 1.0, 0.0],
 [1.0, 3.0, 1.0, 1.0, 3.0, 1.0],
 [1.0, 2.0, 1.0, 1.0, 1.0, 3.0],
 [1.0, 0.0, 4.0, 1.0, 7.0, 2.0],
 [0.0

In [68]:
commit_array[0]

array([ 0.,  1.,  0.,  1.,  1.,  0.])

In [108]:

#평균 구하기
commit_mean = np.mean(commit_array, axis=1)
print("기존 차원: ", commit_mean.shape)

# array 차원 변경
commit_mean = np.reshape(commit_mean, (39,1))
print("변경된 차원: ",commit_mean.shape)


기존 차원:  (39,)
변경된 차원:  (39, 1)


In [109]:
commit_mean[:3]

array([[ 0.5       ],
       [ 0.83333333],
       [ 8.5       ]])

In [73]:
# Try to find value for W and b to compute y_data = x_data * W + b  
# We know that W should be 1 and b should be 0
# But let's TensorFlow figure it out 
W = tf.Variable(tf.random_normal([6,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [84]:
#### Now we can use X and Y in place of x_data and y_data
#### placeholders for a tensor that will be always fed using feed_dict
#### See http://stackoverflow.com/questions/36693740/
X = tf.placeholder(tf.float32, shape=[None, 6])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [85]:
# Out hypothesis XW+b
#hypothesis = X * W + b
# 여러 차원 끼리 비교일 때
hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [86]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train = optimizer.minimize(cost)

In [87]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [113]:
# for step in range(10001):
#     cost_val, W_val, b_val, _ = \
#         sess.run([cost, W, b, train],
#                  feed_dict={X: commit_array, Y:commit_mean})
#     if step % 1000 == 0:
#         print(step, cost_val, W_val, b_val)
        

for step in range(10001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: commit_array, Y: commit_mean})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3.38988e-10 
Prediction:
 [[ 0.50004035]
 [ 0.83334458]
 [ 8.4999752 ]
 [ 1.0000155 ]
 [ 1.8333348 ]
 [ 2.66668701]
 [ 2.66665459]
 [ 1.9999752 ]
 [ 2.16664982]
 [ 2.83331394]
 [ 2.1666677 ]
 [ 0.66670209]
 [ 2.16665697]
 [ 1.66669023]
 [ 2.16666698]
 [ 1.33332646]
 [ 6.16664982]
 [ 9.00002098]
 [ 1.66667223]
 [ 1.33334756]
 [ 2.99998093]
 [ 3.66665888]
 [ 0.83334649]
 [ 1.33332312]
 [ 1.83332455]
 [ 1.83330464]
 [ 1.66665375]
 [ 1.66668034]
 [ 1.50001156]
 [ 2.50000453]
 [ 1.66668034]
 [ 0.66669285]
 [ 2.16668367]
 [ 1.16669285]
 [ 2.66665363]
 [ 0.66669559]
 [ 0.8333562 ]
 [ 0.83335131]
 [ 1.50000715]]
1000 Cost:  2.54577e-10 
Prediction:
 [[ 0.50003481]
 [ 0.83334297]
 [ 8.49997807]
 [ 1.00001335]
 [ 1.83333445]
 [ 2.66668439]
 [ 2.66665578]
 [ 1.99997842]
 [ 2.16665173]
 [ 2.83331609]
 [ 2.16666722]
 [ 0.6666972 ]
 [ 2.16665769]
 [ 1.66668677]
 [ 2.16666651]
 [ 1.33332705]
 [ 6.16665268]
 [ 9.00001812]
 [ 1.66667104]
 [ 1.33334517]
 [ 2.99998283]
 [ 3.66665959]
 [ 0.833344

In [115]:
print(sess.run(hypothesis, feed_dict={X: [[3.0, 3.0, 3.0, 3.0, 3.0, 3.0]]}))

[[ 2.99997735]]
