In [26]:
import numpy as np
import tensorflow as tf
# 모델의 파라미터 값들을 넣는 변수들을 초기화하는 함수 (랜덤으로)
tf.set_random_seed(777)  # for reproducibility

In [27]:
#숫자만 있는 csv
#xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
commit_array = np.genfromtxt('./data/github_commits.csv', delimiter=',')[1:,1:]

In [28]:
commit_array.tolist()

[[0.0, 1.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 4.0, 0.0, 0.0],
 [4.0, 0.0, 4.0, 1.0, 42.0, 0.0],
 [0.0, 1.0, 1.0, 3.0, 1.0, 0.0],
 [1.0, 0.0, 2.0, 3.0, 5.0, 0.0],
 [1.0, 1.0, 1.0, 1.0, 11.0, 1.0],
 [1.0, 0.0, 3.0, 3.0, 6.0, 3.0],
 [1.0, 0.0, 4.0, 4.0, 1.0, 2.0],
 [1.0, 1.0, 3.0, 4.0, 4.0, 0.0],
 [1.0, 1.0, 1.0, 4.0, 5.0, 5.0],
 [1.0, 1.0, 1.0, 3.0, 6.0, 1.0],
 [0.0, 0.0, 1.0, 1.0, 1.0, 1.0],
 [3.0, 2.0, 2.0, 1.0, 5.0, 0.0],
 [1.0, 0.0, 1.0, 1.0, 6.0, 1.0],
 [1.0, 0.0, 2.0, 2.0, 4.0, 4.0],
 [1.0, 0.0, 3.0, 3.0, 0.0, 1.0],
 [0.0, 3.0, 3.0, 4.0, 25.0, 2.0],
 [1.0, 2.0, 1.0, 1.0, 49.0, 0.0],
 [1.0, 5.0, 0.0, 2.0, 2.0, 0.0],
 [1.0, 2.0, 1.0, 1.0, 1.0, 2.0],
 [0.0, 12.0, 1.0, 2.0, 0.0, 3.0],
 [1.0, 5.0, 0.0, 2.0, 9.0, 5.0],
 [1.0, 1.0, 1.0, 2.0, 0.0, 0.0],
 [3.0, 0.0, 0.0, 2.0, 0.0, 3.0],
 [2.0, 2.0, 4.0, 1.0, 2.0, 0.0],
 [4.0, 2.0, 1.0, 2.0, 1.0, 1.0],
 [1.0, 1.0, 4.0, 3.0, 1.0, 0.0],
 [1.0, 3.0, 1.0, 1.0, 3.0, 1.0],
 [1.0, 2.0, 1.0, 1.0, 1.0, 3.0],
 [1.0, 0.0, 4.0, 1.0, 7.0, 2.0],
 [0.0

In [29]:
#평균 구하기
commit_mean = np.mean(commit_array, axis=1)
print("기존 list: ", commit_mean)
print("기존 차원: ", commit_mean.shape)


기존 list:  [ 0.5         0.83333333  8.5         1.          1.83333333  2.66666667
  2.66666667  2.          2.16666667  2.83333333  2.16666667  0.66666667
  2.16666667  1.66666667  2.16666667  1.33333333  6.16666667  9.
  1.66666667  1.33333333  3.          3.66666667  0.83333333  1.33333333
  1.83333333  1.83333333  1.66666667  1.66666667  1.5         2.5
  1.66666667  0.66666667  2.16666667  1.16666667  2.66666667  0.66666667
  0.83333333  0.83333333  1.5       ]
기존 차원:  (39,)


In [30]:
# array 차원 변경
commit_mean = np.reshape(commit_mean, (39,1))
print("변경된 list: ", commit_mean)
print("변경된 차원: ",commit_mean.shape)

변경된 list:  [[ 0.5       ]
 [ 0.83333333]
 [ 8.5       ]
 [ 1.        ]
 [ 1.83333333]
 [ 2.66666667]
 [ 2.66666667]
 [ 2.        ]
 [ 2.16666667]
 [ 2.83333333]
 [ 2.16666667]
 [ 0.66666667]
 [ 2.16666667]
 [ 1.66666667]
 [ 2.16666667]
 [ 1.33333333]
 [ 6.16666667]
 [ 9.        ]
 [ 1.66666667]
 [ 1.33333333]
 [ 3.        ]
 [ 3.66666667]
 [ 0.83333333]
 [ 1.33333333]
 [ 1.83333333]
 [ 1.83333333]
 [ 1.66666667]
 [ 1.66666667]
 [ 1.5       ]
 [ 2.5       ]
 [ 1.66666667]
 [ 0.66666667]
 [ 2.16666667]
 [ 1.16666667]
 [ 2.66666667]
 [ 0.66666667]
 [ 0.83333333]
 [ 0.83333333]
 [ 1.5       ]]
변경된 차원:  (39, 1)


In [31]:
commit_mean[:3]

array([[ 0.5       ],
       [ 0.83333333],
       [ 8.5       ]])

In [32]:
# Try to find value for W and b to compute y_data = x_data * W + b  
# We know that W should be 1 and b should be 0
# But let's TensorFlow figure it out 
W = tf.Variable(tf.random_normal([6,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [33]:
#### Now we can use X and Y in place of x_data and y_data
#### placeholders for a tensor that will be always fed using feed_dict
#### See http://stackoverflow.com/questions/36693740/
X = tf.placeholder(tf.float32, shape=[None, 6])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [34]:
# Out hypothesis XW+b
#hypothesis = X * W + b
# 여러 차원 끼리 비교일 때
hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train = optimizer.minimize(cost)

In [35]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [36]:
for step in range(10001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: commit_array, Y: commit_mean})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  12.9562 
Prediction:
 [[-0.82000834]
 [-4.4951992 ]
 [ 6.93088722]
 [-2.55884171]
 [-0.89232987]
 [ 0.86379558]
 [-0.4550826 ]
 [-1.41795015]
 [-2.04488516]
 [-3.74023485]
 [-2.03478765]
 [ 0.22024381]
 [ 0.70611078]
 [ 0.84714556]
 [-0.21664351]
 [-0.87032622]
 [-1.18834448]
 [ 4.39845848]
 [-3.80082989]
 [-0.7747497 ]
 [-7.28909874]
 [-3.59063959]
 [-1.36231184]
 [-1.59345174]
 [ 1.57079017]
 [-1.53411174]
 [-0.52248698]
 [-0.96572155]
 [-0.87759739]
 [ 2.77468991]
 [ 2.04494047]
 [ 0.43254402]
 [-0.05096298]
 [ 0.74301356]
 [-1.52674174]
 [-0.31260437]
 [-0.06825513]
 [ 0.86850721]
 [ 2.36008835]]
1000 Cost:  0.0851157 
Prediction:
 [[ 0.99425715]
 [ 0.60844028]
 [ 8.31741524]
 [ 1.00256336]
 [ 1.7074995 ]
 [ 2.98430443]
 [ 2.52500582]
 [ 1.62332702]
 [ 1.76364028]
 [ 2.44351244]
 [ 2.0179615 ]
 [ 1.17906773]
 [ 2.19317198]
 [ 2.02865267]
 [ 2.28116465]
 [ 1.21150458]
 [ 5.77531862]
 [ 9.17445278]
 [ 1.66489446]
 [ 1.65108347]
 [ 2.92206955]
 [ 3.63948202]
 [ 0.94433063]
 [

In [38]:
print(sess.run(hypothesis, feed_dict={X: [[3.0, 3.0, 3.0,3,3,3]]}))

[[ 2.91424203]]
