In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [7]:
print(type(a))  
print(a.shape) 

<class 'numpy.ndarray'>
(3,)


In [8]:
b = np.array([[1,2,3],[4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# 2차원 배열 일때 안에 것만 가져오기
b[:1,:]

array([[1, 2, 3]])

In [21]:
b.shape

(2, 3)

In [31]:
# 파일에서 곧바로 읽기
np.genfromtxt('./data/github_commits.csv', delimiter=',')[:3]

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,   0.,   1.,   0.,   1.,   1.,   0.],
       [ nan,   0.,   1.,   0.,   4.,   0.,   0.]])

In [30]:
np.genfromtxt('./data/github_commits.csv', delimiter=',')[1:,1:]

array([[  0.,   1.,   0.,   1.,   1.,   0.],
       [  0.,   1.,   0.,   4.,   0.,   0.],
       [  4.,   0.,   4.,   1.,  42.,   0.],
       [  0.,   1.,   1.,   3.,   1.,   0.],
       [  1.,   0.,   2.,   3.,   5.,   0.],
       [  1.,   1.,   1.,   1.,  11.,   1.],
       [  1.,   0.,   3.,   3.,   6.,   3.],
       [  1.,   0.,   4.,   4.,   1.,   2.],
       [  1.,   1.,   3.,   4.,   4.,   0.],
       [  1.,   1.,   1.,   4.,   5.,   5.],
       [  1.,   1.,   1.,   3.,   6.,   1.],
       [  0.,   0.,   1.,   1.,   1.,   1.],
       [  3.,   2.,   2.,   1.,   5.,   0.],
       [  1.,   0.,   1.,   1.,   6.,   1.],
       [  1.,   0.,   2.,   2.,   4.,   4.],
       [  1.,   0.,   3.,   3.,   0.,   1.],
       [  0.,   3.,   3.,   4.,  25.,   2.],
       [  1.,   2.,   1.,   1.,  49.,   0.],
       [  1.,   5.,   0.,   2.,   2.,   0.],
       [  1.,   2.,   1.,   1.,   1.,   2.],
       [  0.,  12.,   1.,   2.,   0.,   3.],
       [  1.,   5.,   0.,   2.,   9.,   5.],
       [  

In [97]:
# string으로 읽은 후 numpy로 읽기
fileName="./data/github_commits.csv"
textFile = open(fileName, "r", encoding="utf8")
textlist = textFile.read().split("\n")
textlist_range = textlist[1:len(textlist)-1]
# textlist_range[0].split(",")[1:]
# textnumpy = np.empty(6)
# numpy2 = np.empty(6)
# textnumpy
# np.concatenate(textnumpy,numpy2)
# for i in textlist_range:
#     np.append(textnumpy,i.split(",")[1:])
    
# textnumpy
#np.asarray(textFile.read().split("\n"))

#text = np.asarray(textFile.readlines())
#text

TypeError: only integer scalar arrays can be converted to a scalar index